// src/vue/image-masonry.vue
<template>
  <div class="image-masonry" :class="{'is-resizing': isResizing}">
    <div data-resizer></div>
    <div class="image-masonry-container" :style="{'width': width + 'px'}">
      <div
        v-for="image in scaledImages"
        :key="image.src"
        class="masonry-item"
        :style="makeStyle(image)"
        @click="onClick(image.index, $event)"
      >
        <lazy-image
          class="masonry-image"
          :src="image.src"
          :alt="image.alt"
          :srcset="image.srcset"
        />
        <slot :image="image" :index="index"></slot>
      </div>
    </div>
  </div>
</template>

<script>
  import createLayout from '../common/justified-layout';
  import elementResizeEvent, { unbind } from 'element-resize-event';
  import lazyImage from './lazy-image.vue';
  import { debounce } from '../common/utils';

  export default {
    props: {
      images: {
        type: Array,
        required: true,
        default: []
      },
      targetRowHeight: {
        type: Number,
        default: 220
      },
      padding: {
        type: Number,
        default: 4
      }
    },
    data: () => ({
      scaledImages: [],
      width: 0,
      isResizing: false
    }),
    components: {
      lazyImage
    },
    methods: {
      makeStyle({ scaledHeight, scaledWidth, isLastInRow, isLastRow }) {
        let mr = this.padding + 'px';
        const mb = isLastRow ? '0' : mr;
        let flex = `0 0 ${scaledWidth}px`;
        if (isLastInRow) {
          mr = '0';
          flex = `1 1 ${scaledWidth-4}px`;
        }
        return {
          height: scaledHeight + 'px',
          flex: flex,
          'margin-right': mr,
          'margin-bottom': mb
        }
      },
      onClick(index, event) {
        this.$emit('image-click', this.images[index], index, event);
      }
    },
    mounted() {
      const process = () => {
        this.width = this.$el.getBoundingClientRect().width;
        this.scaledImages = createLayout({
          images: this.images,
          containerWidth: this.width,
          targetHeight: this.targetRowHeight,
          padding: this.padding
        });
      };

      const el = this.$el.querySelector('[data-resizer]');
      const resizedFinished = debounce(() => {
        this.isResizing = false;
      }, 100);

      elementResizeEvent(el, () => {
        if (Math.round(this.width) !== Math.round(el.getBoundingClientRect().width)) {
          this.isResizing = true;
          process();
          resizedFinished();
        }
      });

      this.$watch('images', () => {
        process();
      }, {
        immediate: true,
        deep: true
      });

      this.$watch('targetRowHeight', process);
    },
    beforeDestroy() {
      unbind(this.$el);
    }
  };
</script>

<style scoped src="../common/style.css"></style>

// src/svelte/ImageMasonry.svelte
<script>
  import { onMount, createEventDispatcher } from 'svelte';
  import createLayout from '../common/justified-layout';
  import elementResizeEvent, { unbind } from 'element-resize-event';
  import LazyImage from './LazyImage.svelte';
  import { debounce } from '../common/utils';

  function makeStyle({ scaledWidth, scaledHeight, isLastInRow, isLastRow }) {
    let mr = padding + 'px';
    const mb = isLastRow ? '0' : mr;
    let flex = `0 0 ${scaledWidth}px`;
    if (isLastInRow) {
      mr = '0';
      flex = `1 1 ${scaledWidth-4}px`;
    }
    return `height:${scaledHeight}px; flex: ${flex}; margin-right:${mr}; margin-bottom: ${mb}`;
  }

  function onClick(index) {
    dispatch('image-click', {
      image: images[index],
      index
    });
  }

  const dispatch = createEventDispatcher();

  // props
  export let images = [];
  export let targetRowHeight = 220;
  export let padding = 4;

  // state
  let element;
  let scaledImages = [];
  let width;
  let isResizing = false;

  // reactive statement
  $: if (width) {
    scaledImages = createLayout({
      images,
      containerWidth: width,
      targetHeight: targetRowHeight,
      padding
    });
  }

  onMount(() => {
    width = element.getBoundingClientRect().width;

    const resizedFinished = debounce(() => {
      isResizing = false;
    }, 100);

    elementResizeEvent(element, () => {
      if (Math.round(width) !== Math.round(element.getBoundingClientRect().width)) {
        isResizing = true;
        width = element.getBoundingClientRect().width;
      }
    });

    return () => unbind(element);
  });
</script>

<div class="image-masonry {isResizing ? 'is-resizing' : ''}">
  <div data-resizer bind:this={element}></div>
  <div class="image-masonry-container" style="width: {width}px">
    {#each scaledImages as image (image.src)}
      <div class="masonry-item" style={makeStyle(image)} on:click={()=>onClick(image.index)}>
        <LazyImage {...image} />
        <slot image={image}></slot>
      </div>
    {/each}
  </div>
</div>

<style src="../common/style.css"></style>
