// docs/src/react/Advanced.jsx
import { useState, useRef } from 'react';
import ImageMasonry from '../../../src/react/ImageMasonry.jsx';
import sampleImages from '../images';
import openPhotoSwipe from '../photoswipe';
import styles from '../image-details.css';

function shuffleArray(array) {
  for (let i = array.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [array[i], array[j]] = [array[j], array[i]];
  }
}

function ImageDetails(image) {
  return (
    <div className={styles['image-masonry-overlay']}>
      <div className={styles['image-masonry-text']}>{image.title}</div>
    </div>
  )
}

export default function () {

  const [images, setImages] = useState(sampleImages);
  const [rowHeight, setRowHeight] = useState(200);

  const element = useRef(null);

  const handleChangeImagesClick = () => {
    const newArray = [...images];
    shuffleArray(newArray);
    setImages(newArray);
  }

  const handleChangeRowHeightClick = () => {
    setRowHeight(rowHeight + 50);
  }

  const handleImageClick = (image, index) => {
    openPhotoSwipe(images, index, {
      container: element.current,
      selector: '.image-masonry-item'
    });
  }

  return (
    <div>
      <div className="pb-3 text-right">
        <button className="btn btn-light btn-sm" type="button" onClick={handleChangeImagesClick}>Shuffle images</button>&nbsp;
        <button className="btn btn-light btn-sm" type="button" onClick={handleChangeRowHeightClick}>Increase row height</button>
      </div>
      <div ref={element}>
        <ImageMasonry images={images} targetRowHeight={rowHeight} render={ImageDetails} onImageClick={handleImageClick} />
      </div>
    </div>
  )

}

// docs/src/vue/advanced.vue
<template>
  <div>
    <div class="pb-3 text-right">
      <button class="btn btn-light btn-sm" type="button" @click="onChangeImages">Shuffle images</button>
      <button class="btn btn-light btn-sm" type="button" @click="onChangeRowHeight">Increase row height</button>
    </div>

    <image-masonry :images="images" :targetRowHeight="targetRowHeight" @image-click="onClick" ref="imageMasonry">
      <template v-slot="{image}">
        <div class="image-masonry-overlay">
          <div class="image-masonry-text">{{image.title}}</div>
        </div>
      </template>
    </image-masonry>
  </div>
</template>

<script>
import sampleImages from '../images';
import imageMasonry from '../../../src/vue/image-masonry.vue';
import openPhotoSwipe from '../photoswipe';

function shuffleArray(array) {
  for (let i = array.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [array[i], array[j]] = [array[j], array[i]];
  }
}

export default {
  data: () => ({
    images: sampleImages,
    targetRowHeight: 220
  }),
  components: {
    imageMasonry
  },
  methods: {
    onChangeImages() {
      const newArray = [...sampleImages];
      shuffleArray(newArray);
      this.images = newArray;
    },
    onChangeRowHeight() {
      this.targetRowHeight = this.targetRowHeight + 50
    },
    onClick(image, index) {
      openPhotoSwipe(this.images, index, {
        container: this.$refs.imageMasonry.$el,
        selector: '.image-masonry-item'
      });
    }
  }
}
</script>

<style src="../image-details.css"></style>
