// docs/src/react/components/ImageOverlay.jsx
import { useState, useEffect, useRef } from 'react';
import Checkbox from './Checkbox.jsx';
import styles from '../../less/image-overlay.less';

export default function ImageOverlay({
  image,
  selectMode,
  onSelectChange,
  onView
}) {

  const [isSelected, setIsSelected] = useState(false);
  const [isHovering, setIsHovering] = useState(false);

  const handleMouseEnter = () => setIsHovering(true);
  const handleMouseLeave = () => setIsHovering(false);
  const handleChange = value => {
    setIsSelected(value);
  }
  const handleClick = () => {
    if (selectMode) {
      setIsSelected(!isSelected);
    } else {
      onView(image.index);
    }
  }
  const handleMagnifyClick = e => {
    e.stopPropagation();
    onView(image.index);
  }

  useEffect(() => {
    onSelectChange(isSelected, image.index);
  }, [isSelected]);

  const classNames = [styles['image-overlay']];
  isSelected && classNames.push(styles['is-selected']);
  selectMode && classNames.push(styles['select-mode']);

  return (
    <div className={classNames.join(' ')} onClick={handleClick} onMouseEnter={handleMouseEnter} onMouseLeave={handleMouseLeave}>
      <Checkbox
        className={styles['image-checkbox']}
        highlight={selectMode}
        hover={isHovering}
        onChange={handleChange}
        checked={isSelected}
      />
      <button type="button" onClick={handleMagnifyClick} className={styles['image-magnify']} >
        <svg viewBox="0 0 24 24"><path d="M15.5 14h-.79l-.28-.27A6.471 6.471 0 0 0 16 9.5 6.5 6.5 0 1 0 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14zm1-7.5h-2v2h-2v2h2v2h2v-2h2v-2h-2z"></path></svg>
      </button>
    </div>
  )
}

// docs/src/angular/advanced-example/components/image-overlay/image-overlay.component.ts
import { Component, Input, EventEmitter, Output, HostBinding, HostListener } from '@angular/core';

@Component({
  selector: 'image-overlay',
  templateUrl: './image-overlay.component.html',
  styleUrls: ['./image-overlay.less'],
  host: {
    class: 'image-overlay'
  }
})
export class ImageOverlayComponent {
  @Input() image: ScaledImage;
  @Input() selectMode: boolean;
  @Output() selectChange = new EventEmitter();
  @Output() view = new EventEmitter();

  @HostBinding('class.select-mode') get isSelectMode() { return this.selectMode };
  @HostBinding('class.is-selected') isSelected:boolean = false;
  isHovering = false;

  @HostListener('click') onClick() {
    if(this.selectMode) {
      this.isSelected = !this.isSelected;
      this.onChange(this.isSelected)
    } else {
      this.view.emit(this.image.index);
    }
  }

  @HostListener('mouseenter') onMouseEnter() {
    this.isHovering = true;
  }

  @HostListener('mouseleave') onMouseLeave() {
    this.isHovering = false;
  }

  onChange(value: boolean) {
    this.selectChange.emit({value, index: this.image.index});
  }

  onMagnifyClick(e: MouseEvent) {
    e.stopPropagation();
    this.view.emit(this.image.index);
  }
}

<checkbox
  [(ngModel)]="isSelected"
  (ngModelChange)="onChange($event)"
  [highlight]="selectMode"
  [hover]="isHovering"
  class="image-checkbox"
></checkbox>
<!--<div class="image-text">{{image.title}}</div> -->
<button type="button" (click)="onMagnifyClick($event)" class="image-magnify">
  <svg viewBox="0 0 24 24"><path d="M15.5 14h-.79l-.28-.27A6.471 6.471 0 0 0 16 9.5 6.5 6.5 0 1 0 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14zm1-7.5h-2v2h-2v2h2v2h2v-2h2v-2h-2z"></path></svg>
</button>
