// docs/src/vue/components/image-overlay.vue
<template>
  <div
    class="image-overlay"
    :class="{'is-selected': isSelected, 'select-mode': selectMode}"
    @click="onClick"
    @mouseenter="onMouseEnter"
    @mouseleave="onMouseLeave"
  >
    <checkbox
      v-model="isSelected"
      class="image-checkbox"
      :highlight="selectMode"
      :hover="isHovering"
      :label="image.title"
    />
    <!-- <div class="image-text">{{image.title}}</div> -->
    <button type="button" @click.stop="onMagnifyClick" class="image-magnify" v-html="svg"></button>
  </div>
</template>

<script>
import checkbox from './checkbox.vue';
import svg from '../../svg/magnify.svg';

export default {
  props: {
    image: Object,
    selectMode: Boolean
  },
  data: () => ({
    isSelected: false,
    isHovering: false,
    svg
  }),
  components: {
    checkbox
  },
  mounted() {
    this.$watch('isSelected', v => {
      this.$emit('select-change', v, this.image.index);
    });
  },
  methods: {
    onClick() {
      if(this.selectMode) {
        this.isSelected = !this.isSelected;
      } else {
        this.$emit('view', this.image);
      }
    },
    onMagnifyClick(){
      this.$emit('view', this.image);
    },
    onMouseEnter() {
      this.isHovering = true;
    },
    onMouseLeave() {
      this.isHovering = false;
    }
  }
}
</script>

<style lang="less">
  @import '../../style/image-overlay.less';

  .image-overlay {
    @image-overlay();
  }

  .image-text {
    @image-text();
  }

  .image-checkbox {
    @image-checkbox();
  }

  .image-magnify {
    @image-magnify();
  }

  .select-mode {
    @select-mode();
  }
</style>

// docs/src/angular/advanced-example/components/image-overlay/image-overlay.component.ts
import { Component, Input, EventEmitter, Output, HostBinding, HostListener } from '@angular/core';

@Component({
  selector: 'image-overlay',
  templateUrl: './image-overlay.component.html',
  styleUrls: ['./image-overlay.less'],
  host: {
    class: 'image-overlay'
  }
})
export class ImageOverlayComponent {
  @Input() image: ScaledImage;
  @Input() selectMode: boolean;
  @Output() selectChange = new EventEmitter();
  @Output() view = new EventEmitter();

  @HostBinding('class.select-mode') get isSelectMode() { return this.selectMode };
  @HostBinding('class.is-selected') isSelected:boolean = false;
  isHovering = false;

  @HostListener('click') onClick() {
    if(this.selectMode) {
      this.isSelected = !this.isSelected;
      this.onChange(this.isSelected)
    } else {
      this.view.emit(this.image.index);
    }
  }

  @HostListener('mouseenter') onMouseEnter() {
    this.isHovering = true;
  }

  @HostListener('mouseleave') onMouseLeave() {
    this.isHovering = false;
  }

  onChange(value: boolean) {
    this.selectChange.emit({value, index: this.image.index});
  }

  onMagnifyClick(e: MouseEvent) {
    e.stopPropagation();
    this.view.emit(this.image.index);
  }
}

<checkbox
  [(ngModel)]="isSelected"
  (ngModelChange)="onChange($event)"
  [highlight]="selectMode"
  [hover]="isHovering"
  class="image-checkbox"
></checkbox>
<!--<div class="image-text">{{image.title}}</div> -->
<button type="button" (click)="onMagnifyClick($event)" class="image-magnify">
  <svg viewBox="0 0 24 24"><path d="M15.5 14h-.79l-.28-.27A6.471 6.471 0 0 0 16 9.5 6.5 6.5 0 1 0 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14zm1-7.5h-2v2h-2v2h2v2h2v-2h2v-2h-2z"></path></svg>
</button>
