// docs/src/angular/app.component.ts
import { Component } from '@angular/core';
import images from '../images';

function shuffleArray(array) {
  for (let i = array.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [array[i], array[j]] = [array[j], array[i]];
  }
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'angular-image-masonry';
  images = images;
  targetRowHeight = 200;

  onChangeImages () {
    const newArray = [...images];
    shuffleArray(newArray);
    this.images = newArray;
  }

  onChangeRowHeight() {
    this.targetRowHeight = this.targetRowHeight + 20
  }

}

<div>
  <button type="button" (click)="onChangeImages()">Change images</button>   <button type="button" (click)="onChangeRowHeight()">Change row height</button>
  <image-masonry [images]="images" [targetRowHeight]="targetRowHeight"></image-masonry>
</div>

// docs/src/svelte/App.svelte
<script>
  import ImageMasonry from "../../../src/svelte/ImageMasonry.svelte";
  import sampleImages from "../images";

  function shuffleArray(array) {
    for (let i = array.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [array[i], array[j]] = [array[j], array[i]];
    }
  }

  let images = sampleImages;
  let targetRowHeight = 200;

  function onChangeImages() {
    const newArray = [...sampleImages];
    shuffleArray(newArray);
    images = newArray;
  }

  function onChangeRowHeight() {
    targetRowHeight = targetRowHeight + 20
  }

</script>

<button type="button" on:click={onChangeImages}>Change images</button> <button type="button" on:click={onChangeRowHeight}>Change row height</button>
<ImageMasonry images={images} targetRowHeight={targetRowHeight}/>
