// src/angular/image-masonry.component.ts
import { Component, Input, OnInit, OnChanges, OnDestroy, ElementRef, ChangeDetectorRef, SimpleChanges, ContentChild, TemplateRef, EventEmitter, Output, HostBinding } from '@angular/core';
import createLayout from '../common/justified-layout.js';
import elementResizeEvent, { unbind } from 'element-resize-event';
import { debounce } from '../common/utils';

@Component({
  selector: 'image-masonry',
  templateUrl: './image-masonry.component.html',
  styleUrls: ['./image-masonry.component.less'],
  host: {
    class: 'image-masonry'
  }
})
export class ImageMasonryComponent implements OnInit, OnChanges, OnDestroy {
  constructor(private elementRef: ElementRef, private changeDetectorRef: ChangeDetectorRef) { }
  @Output() imageClick: EventEmitter<any> = new EventEmitter();
  @ContentChild('imageDetails', { static: false }) imageDetailsTmpl: TemplateRef<any>;
  @Input() images: any[];
  @Input() targetRowHeight: number = 220;
  @Input() padding: number = 4;

  @HostBinding('class.is-resizing') isResizing:boolean = false;
  scaledImages: ScaledImage[] = [];
  width = 0;

  ngOnInit() {
    const el: Element = this.elementRef.nativeElement.querySelector('[data-resizer]');
    const resizedFinished = debounce(() => {
      this.isResizing = false;
      this.changeDetectorRef.detectChanges();
    }, 100);
    elementResizeEvent(el, () => {
      if (Math.round(this.width) !== Math.round(el.getBoundingClientRect().width)) {
        this.isResizing = true;
        this.process();
        this.changeDetectorRef.detectChanges();
        resizedFinished();
      }
    });
  }

  ngOnChanges(changes: SimpleChanges) {
    if (changes.images || changes.targetRowHeight) {
      this.process();
    }
  }

  ngOnDestroy() {
    unbind(this.elementRef.nativeElement);
  }

  process() {
    this.width = this.elementRef.nativeElement.getBoundingClientRect().width;
    this.scaledImages = createLayout({
      images: this.images,
      containerWidth: this.width,
      targetHeight: this.targetRowHeight,
      padding: this.padding
    })
  }

  makeStyle({ scaledWidth, scaledHeight, isLastInRow, isLastRow }: ScaledImage) {
    let mr = this.padding + 'px';
    const mb = isLastRow ? '0' : mr;
    let flex = `0 0 ${scaledWidth}px`;
    if (isLastInRow) {
      mr = '0';
      flex = `1 1 ${scaledWidth-4}px`;
    }
    return {
      height: scaledHeight + 'px',
      flex: flex,
      'margin-right': mr,
      'margin-bottom': mb
    }
  }

  onClick(index: number, event: any) {
    this.imageClick.emit({
      image: this.images[index],
      index,
      event
    });
  }

  identify(index: number, item: ScaledImage) {
    return item.src;
  }
}

<div data-resizer></div>
<div class="image-masonry-container" [ngStyle]="{'width' : width + 'px'}">
  <div *ngFor="let image of scaledImages; trackBy:identify" class="masonry-item" [ngStyle]="makeStyle(image)" (click)="onClick(image.index, $event)">
    <ng-container *ngTemplateOutlet="imageDetailsTmpl, context: { $implicit: image }"></ng-container>
    <lazy-image [src]="image.src" [srcset]="image.srcset" [alt]="image.alt"></lazy-image>
  </div>
</div>

// src/vue/image-masonry.vue
<template>
  <div class="image-masonry" :class="{'is-resizing': isResizing}">
    <div data-resizer></div>
    <div class="image-masonry-container" :style="{'width': width + 'px'}">
      <div
        v-for="image in scaledImages"
        :key="image.src"
        class="masonry-item"
        :style="makeStyle(image)"
        @click="onClick(image.index, $event)"
      >
        <lazy-image
          class="masonry-image"
          :src="image.src"
          :alt="image.alt"
          :srcset="image.srcset"
        />
        <slot :image="image" :index="index"></slot>
      </div>
    </div>
  </div>
</template>

<script>
  import createLayout from '../common/justified-layout';
  import elementResizeEvent, { unbind } from 'element-resize-event';
  import lazyImage from './lazy-image.vue';
  import { debounce } from '../common/utils';

  export default {
    props: {
      images: {
        type: Array,
        required: true,
        default: []
      },
      targetRowHeight: {
        type: Number,
        default: 220
      },
      padding: {
        type: Number,
        default: 4
      }
    },
    data: () => ({
      scaledImages: [],
      width: 0,
      isResizing: false
    }),
    components: {
      lazyImage
    },
    methods: {
      makeStyle({ scaledHeight, scaledWidth, isLastInRow, isLastRow }) {
        let mr = this.padding + 'px';
        const mb = isLastRow ? '0' : mr;
        let flex = `0 0 ${scaledWidth}px`;
        if (isLastInRow) {
          mr = '0';
          flex = `1 1 ${scaledWidth-4}px`;
        }
        return {
          height: scaledHeight + 'px',
          flex: flex,
          'margin-right': mr,
          'margin-bottom': mb
        }
      },
      onClick(index, event) {
        this.$emit('image-click', this.images[index], index, event);
      }
    },
    mounted() {
      const process = () => {
        this.width = this.$el.getBoundingClientRect().width;
        this.scaledImages = createLayout({
          images: this.images,
          containerWidth: this.width,
          targetHeight: this.targetRowHeight,
          padding: this.padding
        });
      };

      const el = this.$el.querySelector('[data-resizer]');
      const resizedFinished = debounce(() => {
        this.isResizing = false;
      }, 100);

      elementResizeEvent(el, () => {
        if (Math.round(this.width) !== Math.round(el.getBoundingClientRect().width)) {
          this.isResizing = true;
          process();
          resizedFinished();
        }
      });

      this.$watch('images', () => {
        process();
      }, {
        immediate: true,
        deep: true
      });

      this.$watch('targetRowHeight', process);
    },
    beforeDestroy() {
      unbind(this.$el);
    }
  };
</script>

<style scoped src="../common/style.css"></style>
