// src/angular/lazy-image/lazy-image.component.ts
import { Component, AfterContentInit, Input, ElementRef, ChangeDetectorRef } from '@angular/core';
import { isInViewport } from '../../common/utils';

const cache = {};

@Component({
  selector: 'lazy-image',
  templateUrl: './lazy-image.component.html',
  styleUrls: ['../../common/lazy-image.css'],
  host: { 'class': 'lazy-image-container', 'data-masonry-image': '' }
})
export class LazyImageComponent implements AfterContentInit {
  constructor(private elementRef: ElementRef, private changeDetectorRef: ChangeDetectorRef) {}

  @Input() src: string;
  @Input() srcset: string;
  @Input() alt: string;
  @Input() emitter: object;

  isLoaded = false;
  isVisible = false;
  _lazy_image_check = null;

  onLoad() {
    cache[this.src] = true;
    this.isLoaded = true;
    this.changeDetectorRef.detectChanges();
  }

  ngAfterContentInit() {
    if (cache[this.src]) {
      this.isVisible = true;
      this.isLoaded = true;
    }

    if (this.isLoaded) {
      return;
    }

    const checkIsVisible = () => {
      if (isInViewport(this.elementRef.nativeElement)) {
        this.emitter.off('viewportChange', checkIsVisible);
        this.isVisible = true;
      }
    }
    this.emitter.on('viewportChange', checkIsVisible);
    checkIsVisible();
    this._lazy_image_check = checkIsVisible;
  }

  ngOnDestroy() {
    this.emitter.off('viewportChange', this._lazy_image_check);
  }

}

<img
  *ngIf="isVisible"
  class="lazy-image"
  [class.is-loaded]="isLoaded"
  (load)="onLoad()"
  [attr.src]="src"
  [attr.alt]="alt"
  [attr.srcset]="srcset"
/>

// src/vue/lazy-image.vue
<template>
  <div data-masonry-image class="lazy-image-container" :class="{'is-loaded': isLoaded}">
    <img
      v-if="isVisible"
      class="lazy-image"
      :class="{'is-loaded': isLoaded}"
      @load="onLoad()"
      :src="src"
      :alt="alt"
      :srcset="srcset"
    />
  </div>
</template>

<script>
import { isInViewport } from '../common/utils';

const cache = {};

export default {
  props: {
    src: String,
    alt: String,
    srcset: String,
    emitter: null
  },
  data: () => ({
    isLoaded: false,
    isVisible: false
  }),
  created() {
    if(cache[this.src]) {
      this.isLoaded = true;
      this.isVisible = true;
    }
  },
  mounted() {
    if (this.isLoaded) {
      return;
    }

    const checkIsVisible = () => {
      if (isInViewport(this.$el)) {
        this.emitter.off('viewportChange', checkIsVisible);
        this.isVisible = true;
      }
    }
    this.emitter.on('viewportChange', checkIsVisible);
    this._lazy_image_check = checkIsVisible;
    checkIsVisible();
  },
  destroyed() {
    this.emitter.off('viewportChange', this._lazy_image_check);
  },
  methods: {
    onLoad() {
      cache[this.src] = true;
      this.isLoaded = true;
    }
  }
};
</script>

<style scoped src="../common/lazy-image.css"></style>
